{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ionic.libs",
    "module": "ionfilesystem-android",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ionfilesystem-android-1.1.0.aar",
          "url": "ionfilesystem-android-1.1.0.aar",
          "size": 170343,
          "sha512": "8802d82dc2491372ec983801c94736066910b4c0a26dca93953e20ef29e50361b820cd4c1d50f20ffc482b1612f9e263f4923b90aa091bd9c4351cf1cad7b8df",
          "sha256": "a41d796245fd79c6d374ab2c449f8b29a577a8b1fd43efd5ab1f1068d13ae303",
          "sha1": "1bc03a3d6918c6217b0399f9ff048144bce0c63c",
          "md5": "9e4c5113801b92c77dc9e0c505b1d7d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ionfilesystem-android-1.1.0.aar",
          "url": "ionfilesystem-android-1.1.0.aar",
          "size": 170343,
          "sha512": "8802d82dc2491372ec983801c94736066910b4c0a26dca93953e20ef29e50361b820cd4c1d50f20ffc482b1612f9e263f4923b90aa091bd9c4351cf1cad7b8df",
          "sha256": "a41d796245fd79c6d374ab2c449f8b29a577a8b1fd43efd5ab1f1068d13ae303",
          "sha1": "1bc03a3d6918c6217b0399f9ff048144bce0c63c",
          "md5": "9e4c5113801b92c77dc9e0c505b1d7d1"
        }
      ]
    }
  ]
}
