{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "activity-ktx is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "activity-ktx is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.9.3.aar",
          "url": "activity-ktx-1.9.3.aar",
          "size": 2130,
          "sha512": "76c1311dfe43c8cfcbaae64811e3a0ea8e6a27278933d09f48bca4bb25fde0be4f669ff122b53afe8a6b66d9acbcee0561921e9456a6f713cd728c54f9331437",
          "sha256": "e2da34f68cac557986280198e5c1546b8a245269b050b1cc90b56916dbf69201",
          "sha1": "a1ac8704cfd955139ae60b07a8fcfc6cab8f218b",
          "md5": "f06d8d1cb866a970f46e2bc7d411733f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "activity-ktx is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "activity-ktx is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.9.3.aar",
          "url": "activity-ktx-1.9.3.aar",
          "size": 2130,
          "sha512": "76c1311dfe43c8cfcbaae64811e3a0ea8e6a27278933d09f48bca4bb25fde0be4f669ff122b53afe8a6b66d9acbcee0561921e9456a6f713cd728c54f9331437",
          "sha256": "e2da34f68cac557986280198e5c1546b8a245269b050b1cc90b56916dbf69201",
          "sha1": "a1ac8704cfd955139ae60b07a8fcfc6cab8f218b",
          "md5": "f06d8d1cb866a970f46e2bc7d411733f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "activity-ktx is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "activity-ktx is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.9.3-sources.jar",
          "url": "activity-ktx-1.9.3-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "activity-ktx is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "activity-ktx is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.9.3-versionMetadata.json",
          "url": "activity-ktx-1.9.3-versionMetadata.json",
          "size": 2769,
          "sha512": "effecf94bfb9ca6086d62380a2b1768168933103bef12b68868124607f70f883191b252bb890cef4e565dfd03ff8483f6bb9476b4a9d78f999c5583add8f61f4",
          "sha256": "593878f55a9903bc6e6eb05aac98f8d9213ee1ae9f71d087deaf178e21a2119d",
          "sha1": "60a9709fbb062d5b57d2fc82dc93ed8fe9268301",
          "md5": "1ff2ae741a65d0782775d36805a0ce3d"
        }
      ]
    }
  ]
}